kirigami-addons: Autospec creation for update from version 1.6.0 to version 1.7.0
Alexander Lohnau (3):
      Avoid QtQml and QtQuickTest module includes
      Include KDEClangFormat cmake module
      Fix various clazy warnings

Carl Schwan (44):
      RadioSelector: Use style from Marknote version
      Update AboutKDEPage bug report address
      Add icons to buttons in AboutKDEPage
      Use a slighly less grey background color for FormCardPage
      Update templates
      Add a shortcut configuration module
      ShortcutsConfigurationModule: Add application property
      ShortcutsEditor: Unset currentIndex
      Fix multiple issues with ShortcutsEditor
      Explicitely force hoverEnabled
      Reduce unqualified access in TreeViewDecoration
      Fix tree navigation button not being clickable
      Add ECMAddAndroidApk to templates
      Also use ecm_add_android_apk in templates
      Make Avatar async by default
      Improve mobile mode from MessageDialog
      Introduce ContextMenu component
      ContextMenu: Correctly implement submenu actions for desktop mode
      MessageDialog: Better handle MessageDialog without footer
      Port away from deprecated Connection code
      Support headerContentItem in ContextMenu
      ContextMenu: Don't show next icon for button without sub actions
      ConfigWindow: Fix warning
      Load ContextMenu implementation when needed
      Make BottomDrawer work in plain QQC2.ApplicationWindow
      ContextMenu::popup add optional argument position
      Rename ContextMenu to ConvergentContextMenu
      Better handling of invisble submenu
      BottomDrawer: Better handle empty ApplicationWindow
      Allow providing a parent for ConvergentContextMenu
      ContentItemLoader: Silence some warnings
      Add support for AutoExclusive
      Fix submenu not being visible anymore
      Add support for checkable button in ContextMenuPage
      Add support for displayComponent in ContextMenuPage
      AlbumMaximizeComponent: Expose currentIndex from view
      Only try to auto play media file if a playAction is associated
      Cleanup FormComboBoxDelegate implementation
      IndicatorItemDelegate: Add support for drag and drop api
      RoundedItemDelegate: Add support for DropArea
      templates: Bump runtime version to 6.8
      Bump version to 1.7.0
      Provide icon used by Kirigami Addons as variable
      Add more doc for ConvergentContextMenu

Joshua Goins (8):
      AboutPage: Fix incorrect id in "Copy to Clipboard" notification
      StatefulWindow: Port to AboutKDEPage from AboutKDE
      AboutKDEPage: Fix undefined reference to aboutData
      SonnetConfigPage: Increase top margin of the page
      ShortcutsConfigurationModule: Add Kirigami import
      AvatarButton: Add alias to Avatar's asynchronous property
      Avatar: Set the Text to PlainText
      Avatar: Only call NameUtils.isStringUnsuitableForInitials once

Kai Uwe Broulik (1):
      Avatar: Add asynchronous property

Mark Penner (1):
      Fix API documentation link in README.md

Schrijvers Luc (1):
      Disable KF6GlobalAccel on Haiku too

Tomasz Bojczuk (1):
      TimePopup: remove accepted() signal which duplicates Dialog signal

Volker Krause (2):
      Set the correct translation domain everywhere
      Show the KDE Frameworks version in use rather than the one we built against

l10n daemon script (31):
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn